#!/bin/bash
# WFO System Alignment Verification Script
# This script verifies that the entire system is aligned with WFO validation

set -e

# Colors for output
GREEN='\033[0;32m'
RED='\033[0;31m'
YELLOW='\033[1;33m'
NC='\033[0m' # No Color

echo "================================================"
echo "  WFO System Alignment Verification"
echo "================================================"
echo ""

ERRORS=0
WARNINGS=0

# Helper functions
check_pass() {
    echo -e "${GREEN}✅ PASS${NC}: $1"
}

check_fail() {
    echo -e "${RED}❌ FAIL${NC}: $1"
    ((ERRORS++))
}

check_warn() {
    echo -e "${YELLOW}⚠️  WARN${NC}: $1"
    ((WARNINGS++))
}

# ================================================
# 1. Check WFO Files Exist
# ================================================
echo "1. Checking WFO Files..."
echo "   --------------------------------"

if [ -f "backend/models/wfo_validation/wfo_results.json" ]; then
    check_pass "WFO results found"

    # Check number of windows
    WINDOWS=$(cat backend/models/wfo_validation/wfo_results.json | grep -o '"total_windows":[[:space:]]*[0-9]*' | grep -o '[0-9]*$')
    if [ "$WINDOWS" = "8" ]; then
        check_pass "8 WFO windows validated"
    else
        check_fail "Expected 8 windows, found $WINDOWS"
    fi

    # Check consistency
    CONSISTENCY=$(cat backend/models/wfo_validation/wfo_results.json | grep -o '"consistency_rate":[[:space:]]*[0-9.]*' | grep -o '[0-9.]*$')
    if [ "$CONSISTENCY" = "1.0" ] || [ "$CONSISTENCY" = "1" ]; then
        check_pass "100% consistency rate (8/8 windows profitable)"
    else
        check_warn "Consistency rate: $CONSISTENCY (below 100%)"
    fi
else
    check_fail "WFO results not found at backend/models/wfo_validation/wfo_results.json"
fi

echo ""

# ================================================
# 2. Check API Data is WFO-Generated
# ================================================
echo "2. Checking API Data..."
echo "   --------------------------------"

if [ -f "backend/data/backtest_results.json" ]; then
    check_pass "API backtest data found"

    # Check if generated by WFO
    if grep -q "walk_forward_optimization" backend/data/backtest_results.json; then
        check_pass "Backtest data generated by WFO"
    else
        check_fail "Backtest data NOT generated by WFO (old data)"
    fi

    # Check metadata
    if grep -q "\"total_windows\": 8" backend/data/backtest_results.json; then
        check_pass "API data contains 8 WFO windows"
    else
        check_warn "API data may not have all 8 windows"
    fi
else
    check_fail "API backtest data not found at backend/data/backtest_results.json"
fi

echo ""

# ================================================
# 3. Check Documentation
# ================================================
echo "3. Checking Documentation..."
echo "   --------------------------------"

if grep -q "Data Leakage Prevention" CLAUDE.md; then
    check_pass "CLAUDE.md has WFO guidelines"
else
    check_fail "CLAUDE.md missing WFO guidelines"
fi

if grep -q "Walk-Forward Optimization" CLAUDE.md; then
    check_pass "CLAUDE.md references WFO"
else
    check_warn "CLAUDE.md doesn't mention WFO explicitly"
fi

if [ -f "backend/docs/WFO_WINDOW_7_ANALYSIS.md" ]; then
    check_pass "Window 7 analysis documented"
else
    check_warn "Window 7 analysis not found"
fi

if [ -f "backend/docs/WFO_SYSTEM_ALIGNMENT.md" ]; then
    check_pass "System alignment guide exists"
else
    check_warn "System alignment guide not found"
fi

echo ""

# ================================================
# 4. Check Backend Code
# ================================================
echo "4. Checking Backend Code..."
echo "   --------------------------------"

if grep -q "wfo_results.json" backend/src/api/services/performance_service.py; then
    check_pass "Backend loads WFO results"
else
    check_fail "Backend doesn't load WFO results"
fi

if grep -q "_load_wfo_metrics" backend/src/api/services/performance_service.py; then
    check_pass "Backend has WFO metrics loader"
else
    check_warn "Backend may not load WFO metrics dynamically"
fi

echo ""

# ================================================
# 5. Check Production Model
# ================================================
echo "5. Checking Production Model..."
echo "   --------------------------------"

if [ -f "backend/models/mtf_ensemble/training_metadata.json" ]; then
    check_pass "Production model metadata found"

    # Extract training end date
    TRAIN_END=$(cat backend/models/mtf_ensemble/training_metadata.json | grep -o '"data_end":[[:space:]]*"[^"]*"' | cut -d'"' -f4)
    echo "   Training ended: $TRAIN_END"
else
    check_warn "Production model metadata not found"
fi

if [ -d "backend/models/mtf_ensemble" ]; then
    MODEL_COUNT=$(ls -1 backend/models/mtf_ensemble/*.pkl 2>/dev/null | wc -l)
    if [ "$MODEL_COUNT" -ge "3" ]; then
        check_pass "Production models exist ($MODEL_COUNT .pkl files)"
    else
        check_warn "Expected 3+ models, found $MODEL_COUNT"
    fi
fi

echo ""

# ================================================
# 6. Check WFO Windows
# ================================================
echo "6. Checking WFO Window Models..."
echo "   --------------------------------"

WINDOW_COUNT=$(find backend/models/wfo_validation -maxdepth 1 -type d -name "window_*" 2>/dev/null | wc -l)
if [ "$WINDOW_COUNT" -eq "8" ]; then
    check_pass "8 WFO window directories found"
else
    check_warn "Expected 8 window directories, found $WINDOW_COUNT"
fi

echo ""

# ================================================
# Summary
# ================================================
echo "================================================"
echo "  Verification Summary"
echo "================================================"
echo ""

TOTAL_CHECKS=$((ERRORS + WARNINGS))

if [ $ERRORS -eq 0 ] && [ $WARNINGS -eq 0 ]; then
    echo -e "${GREEN}✅ ALL CHECKS PASSED${NC}"
    echo ""
    echo "The system is fully aligned with WFO validation."
    exit 0
elif [ $ERRORS -eq 0 ]; then
    echo -e "${YELLOW}⚠️  PASSED WITH WARNINGS${NC}"
    echo ""
    echo "Errors: $ERRORS"
    echo "Warnings: $WARNINGS"
    echo ""
    echo "The system is functional but some optional components are missing."
    exit 0
else
    echo -e "${RED}❌ VERIFICATION FAILED${NC}"
    echo ""
    echo "Errors: $ERRORS"
    echo "Warnings: $WARNINGS"
    echo ""
    echo "Please fix the errors above before proceeding."
    exit 1
fi
